### ISSUE TITLE
Squash weird bug in the selector page

### ISSUE THREAD

**Issue by sduskis** [skyscreamer/yoga#101]
we can't reproduce it, but we get a weird bug in the selector page.

**Comment by carterpage** [comment]
Saw a version of this bug again briefly tonight.  After redeploying a fresh version to cloudfoundry, I clicked "favoriteArtists", then "albums", then "songs".  Then I disabled the selector by unclicking "favoriteArtists".  The selector was updated at the top, but the preview pane was not updated correctly.

**Comment by sduskis** [comment]
we can't reproduce, moving out of 1.0
