### ISSUE TITLE
fix RunServer for resteasy-demo

### ISSUE THREAD

**Issue by sduskis** [skyscreamer/yoga#112]
Right now, 'mvn jetty:run' works, but RunServer.java doesn't.  It could be because webdefault.xml has to be created as per http://docs.codehaus.org/display/JETTY/How+to+enable+serving+aliased+files

**Comment by carterpage** [comment]
I've got this fixed in one of my branches.  I'll merge it this week.

**Comment by sduskis** [comment]
carter fix this

**Comment by carterpage** [comment]
s/fix/fixed/ i think
