### ISSUE TITLE
No matching bean of type [org.skyscreamer.yoga.metadata.MetaDataRegistry]

### ISSUE THREAD

**Issue by priyatam** [skyscreamer/yoga#187]
versions: yoga-core 0.93, yoga-core-springmvc-0.93. mybatis 3, spring-mybatis.

The examples are outdated and I can't build a working app with the provided demo-springmvc . I updated the example to include dom4j dependencies, exclude hamcrest-all, and add spring config based on the demo springmvc (not example on wiki). I get the following error:

No matching bean of type [org.skyscreamer.yoga.metadata.MetaDataRegistry] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:924)

Am I missing anything? A working wiki on the latest release would be helpful.

**Comment by carterpage** [comment]
Priyatam, thanks for bringing this to our attention.  We're in the process of getting ready for our 1.0 release, and we'll be cleaning up the documentation and any outstanding bugs in the demos.  We'll update this issue once those components are updated.  We've all got day jobs while we work on this framework, so thanks for being patient!

**Comment by carterpage** [comment]
Our spring-mvc wiki is up-to-date.  There is also a video now that walks through the same functionality.  The latest release, 1.0.0-rc1 should be working well.  Please let us know if you have any further issues.
