### ISSUE TITLE
Add "exclude metadata" checkbox checked by default to selector builder

### ISSUE THREAD

**Issue by carterpage** [skyscreamer/yoga#199]
It's a little confusing to a new user looking at the selector builder what's going on because of all the metadata that is there that suddenly gets excluded when selected.  I think we should have it disabled by default so when they first come to it they see something like:

```
{
id: 1,
name: "Carter Page",
href: "/user/1.json"
}
```

When they start selecting fields on the left it will be immediately apparent that the selections are additive in nature.  It will make it much easier to understand what's going on.

Having the metadata fields (navigationLinks, etc) as a check-box, allows them to re-enable that and see the other goodies the framework provides.

**Comment by sduskis** [comment]
That makes sense.  The user of the builder page already has access to the meta data via the tree mechanism, and doesn't need to see it in the ui.  The json metadata is useful for direct users of the API.

**Comment by carterpage** [comment]
Fixed in #200
