### ISSUE TITLE
Remove Spring dependencies from JAX-RS Support

### ISSUE THREAD

**Issue by kametic** [skyscreamer/yoga#205]
JAX-RS implementation can be integrated by hand, with guice, by spring or other IOC framework. 

Please remove spring dependencies from the jax-rs integration. 

You can use standard JSR-330 @Inject in place of proprietary @Autowired .

**Comment by carterpage** [comment]
Good idea.  +1

**Comment by carterpage** [comment]
This will be fixed in the next release.

**Comment by carterpage** [comment]
Whoops.  211 was closed, not merged.  Still open.

**Comment by sduskis** [comment]
Yeah,

I'm having issues with a limited development environment.  I'll finish this
up tonight.

-Solomon

**Comment by carterpage** [comment]
Fixed.  Will roll out in 1.0.1 this week.
