### ISSUE TITLE
MetaDataController does not deploy in the Jersey-Spring demo

### ISSUE THREAD

**Issue by cepage** [skyscreamer/yoga#219]
The MetaDataController deploys correctly in the SpringMVC demo, and in the Jersey-Guice demo, but not in the Jersey-Spring demo. The constructor is never called for the controller.

**Comment by sduskis** [comment]
I'll fix that, and add a test.

**Comment by sduskis** [comment]
pull request #220 https://github.com/skyscreamer/yoga/pull/220

**Comment by sduskis** [comment]
Can you please retest?  This should be fixed.

**Comment by sduskis** [comment]
Corby retested, and this is fixed.
