### ISSUE TITLE
Add structure meta data

### ISSUE THREAD

**Issue by sduskis** [skyscreamer/yoga#24]
Have a mechanism that exposes available data structures.  If you have a "user" resource that can have selector data, expose what that structure is.  Possibly include the ability to use selectors on the meta data to be able to drill down to structures that are referred to from the primary structure.  For example, if a "user" refers to albums (in the guise of favoriteAlbums), beyond just having a link to the album meta data, have the ability for selectors to drill down into the album meta data.

**Comment by carterpage** [comment]
As I understand it, there will be (for example) a URL like /user/metadata.json or /album/metadata.json, which will provide data about the structure of the user object.

We have also discussed adding some cool tools to the xhtml version of an entity's metadata page that allows a programmer to visually build a selector by clicking/navigating the object model.  More on that in a future issue.
