### ISSUE TITLE
Support Disabling of Explicit Selectors

### ISSUE THREAD

**Issue by carterpage** [skyscreamer/yoga#32]
Some do not want to expose full selector functionality in production. Simple aliasing that requires no coding is an quick solution. (e.g. Alias "/user/1.json?selector=:(friends)" to "/friends/1.json" with a one-line configuration change in run-time.)

**Comment by cepage** [comment]
Handle selector aliases as a request parameter

Allow disabling of explicit (non-aliased) selectors

**Comment by cepage** [comment]
Create an Alias Parser implementation that periodically reloads from property files
